let currentLang = "en";

const translations = {
  "Hinglish": {
    "logo": "Farmify",
    "demo_badge": "Demo Mode",
    "nav_home": "Home",
    "nav_mandi": "Mandi",
    "nav_chat": "Chat",
    "nav_myfarm": "My Farm",
    "nav_store": "Store",
    "nav_profile": "Profile",
    "hero_title": "Kisaan Ka Digital Saathi",
    "hero_sub": "AI-powered farming companion · Hinglish · Offline-ready",
    "pill_1": "120M+ Addressable Users",
    "pill_2": "3x Faster Disease Response",
    "pill_3": "₹15K Saved per Acre",
    "demo_title": "Demo: Try all 13 features",
    "demo_desc": "No login needed, instant access.",
    "btn_scan": "Start Scan →",
    "sec_ai": "AI Features",
    "feat1_title": "Disease Predictor",
    "feat1_desc": "Scan leaf for instant diagnosis",
    "feat2_title": "Krishi Chat AI",
    "feat2_desc": "Voice assistant in Hinglish",
    "feat3_title": "Crop Recommend",
    "feat3_desc": "AI crop suggestions for your soil",
    "feat4_title": "Fertilizer Guide",
    "feat4_desc": "Smart fertilizer recommendations",
    "sec_advisory": "Advisory",
    "adv1_title": "🌧️ Rain Alert – Bhopal",
    "adv1_desc": "Light rain expected Thursday. Delay irrigation by 2 days to save water and fertilizer.",
    "adv2_title": "🐛 Pest Warning – Wheat",
    "adv2_desc": "Aphid activity rising in MP region. Apply neem-based spray early morning for best results.",
    "adv3_title": "💰 Mandi Price Up – Soybean",
    "adv3_desc": "Soybean prices rose ₹180/quintal in Indore mandi today. Good time to sell.",
    "sec_quick": "Quick Actions",
    "act1": "Disease Predictor",
    "act2": "Crop Recommend",
    "act3": "Farm Store",
    "act4": "My Farm",
    "act5": "Farm Community",
    "act6": "Top News",
    "mandi_title": "Mandi Prices",
    "mandi_sub": "Live market rates · Updated daily",
    "mandi_sec_title": "Today's Rates – Indore Mandi",
    "mandi_h1": "Crop",
    "mandi_h2": "Price (₹/Quintal)",
    "mandi_h3": "Change",
    "mandi_h4": "Market",
    "mandi_c1": "Wheat (Gehun)",
    "mandi_c2": "Soybean",
    "mandi_c3": "Maize (Makka)",
    "mandi_c4": "Cotton (Kapas)",
    "mandi_c5": "Gram (Chana)",
    "mandi_c6": "Onion (Pyaaz)",
    "mandi_c7": "Tomato",
    "mandi_c8": "Potato (Aloo)",
    "mandi_loc1": "Indore",
    "mandi_loc2": "Bhopal",
    "mandi_loc3": "Nagpur",
    "mandi_loc4": "Nashik",
    "mandi_loc5": "Pune",
    "mandi_loc6": "Agra",
    "chat_title": "Krishi Chat AI",
    "chat_sub": "Voice assistant in Hinglish · Ask anything about farming",
    "chat_sec_title": "Chat with AI",
    "chat_welcome": "🌿 Namaste Kisan bhai! Main aapka Krishi AI assistant hoon. Koi bhi kheti se judi baat puchh sakte ho!",
    "chat_placeholder": "Apna sawaal likhein... (e.g. Wheat mein konsa fertilizer daalein?)",
    "chat_send": "Send",
    "chat_q1": "🌾 Fasal bimari",
    "chat_q2": "💰 Mandi price",
    "chat_q3": "🌱 Fasal suggest",
    "chat_q4": "🌤️ Mausam",
    "farm_title": "My Farm",
    "farm_sub": "Track your crops, soil, and activity",
    "farm_sec_title": "Farm Overview",
    "farm_c1_t": "Total Area",
    "farm_c1_d": "4.5 Acres – Bhopal",
    "farm_c2_t": "Active Crops",
    "farm_c2_d": "Wheat, Soybean",
    "farm_c3_t": "Soil Health",
    "farm_c3_d": "pH 6.8 – Good",
    "farm_c4_t": "Yield Est.",
    "farm_c4_d": "38 Quintal/Acre",
    "weather_title": "Live Weather",
    "weather_type": "Weather Type :",
    "weather_cond": "Haze",
    "weather_now": "Now",
    "weather_feels": "Feels Like 25.5°C",
    "weather_loc": "Bhopal , IN",
    "weather_pres": "Pressure",
    "weather_hum": "Humidity",
    "weather_wind": "Wind",
    "w_tab1": "Overview",
    "w_tab2": "Wind",
    "w_tab3": "Humidity",
    "w_d1": "Mon",
    "w_d1_desc": "scattered clouds",
    "w_d2": "Tue",
    "w_d2_desc": "few clouds",
    "w_d3": "Wed",
    "w_d3_desc": "clear sky",
    "w_d4": "Thu",
    "w_d4_desc": "clear sky",
    "w_d5": "Fri",
    "w_d5_desc": "clear sky",
    "store_title": "Farm Store",
    "store_sub": "Seeds · Fertilizers · Equipment · Delivered to your farm",
    "store_sec_title": "Featured Products",
    "s_c1_t": "Wheat Seeds HY",
    "s_c1_d": "₹1,200 / 10kg bag",
    "s_c2_t": "DAP Fertilizer",
    "s_c2_d": "₹1,350 / 50kg bag",
    "s_c3_t": "Neem Pesticide",
    "s_c3_d": "₹480 / 1L bottle",
    "s_c4_t": "Drip Kit 1 Acre",
    "s_c4_d": "₹8,500 / set",
    "s_c5_t": "Soybean Seeds",
    "s_c5_d": "₹950 / 10kg bag",
    "s_c6_t": "Soil Test Kit",
    "s_c6_d": "₹699 / kit",
    "scan_modal_title": "AI Disease Predictor",
    "scan_modal_desc": "Upload a picture of your plant leaf, and our AI will diagnose any issues.",
    "scan_upload_btn": "Select Image to Scan",
    "scan_disease": "Disease:",
    "scan_solution": "Solution:",
    "f1": "1. AI Disease Predictor",
    "f1_d": "Scan plants for diseases with AI accuracy.",
    "f2": "2. Krishi Chat AI",
    "f2_d": "Voice-enabled Hinglish chatbot for help.",
    "f3": "3. Crop Recommendation",
    "f3_d": "Best crop suggestions based on soil health.",
    "f4": "4. Fertilizer Guide",
    "f4_d": "Precise NPK split info for maximum yield.",
    "f5": "5. Mandi Prices",
    "f5_d": "Live market rates updated daily.",
    "f6": "6. Weather Intelligence",
    "f6_d": "Hyper-local farm weather updates.",
    "f7": "7. Farm Store",
    "f7_d": "Buy seeds, fertilizers & equipment securely.",
    "f8": "8. Support System",
    "f8_d": "Direct contact with community & experts.",
    "f9": "9. Soil Testing Labs",
    "f9_d": "Find nearest certified testing facilities.",
    "f10": "10. Farm Community",
    "f10_d": "Connect with local farmers and groups.",
    "f11": "11. Govt. Subsidies",
    "f11_d": "Track schemes, grants and national orgs.",
    "f12": "12. Machinery Rental",
    "f12_d": "Rent tractors and hi-tech tools at low cost.",
    "f13": "13. Financial Ledger",
    "f13_d": "Manage farm accounts, income & expenses."
  },
  "English": {
    "logo": "Farmify",
    "demo_badge": "Demo Mode",
    "nav_home": "Home",
    "nav_mandi": "Market",
    "nav_chat": "Chat",
    "nav_myfarm": "My Farm",
    "nav_store": "Store",
    "nav_profile": "Profile",
    "hero_title": "Farmer's Digital Companion",
    "hero_sub": "AI-powered farming companion · English · Offline-ready",
    "pill_1": "120M+ Addressable Users",
    "pill_2": "3x Faster Disease Response",
    "pill_3": "₹15K Saved per Acre",
    "demo_title": "Demo: Try all 13 features",
    "demo_desc": "No login needed, instant access.",
    "btn_scan": "Start Scan →",
    "sec_ai": "AI Features",
    "feat1_title": "Disease Predictor",
    "feat1_desc": "Scan leaf for instant diagnosis",
    "feat2_title": "Krishi Chat AI",
    "feat2_desc": "Voice assistant in English",
    "feat3_title": "Crop Recommend",
    "feat3_desc": "AI crop suggestions for your soil",
    "feat4_title": "Fertilizer Guide",
    "feat4_desc": "Smart fertilizer recommendations",
    "sec_advisory": "Advisory",
    "adv1_title": "🌧️ Rain Alert – Bhopal",
    "adv1_desc": "Light rain expected Thursday. Delay irrigation by 2 days to save water and fertilizer.",
    "adv2_title": "🐛 Pest Warning – Wheat",
    "adv2_desc": "Aphid activity rising in MP region. Apply neem-based spray early morning for best results.",
    "adv3_title": "💰 Market Price Up – Soybean",
    "adv3_desc": "Soybean prices rose ₹180/quintal in Indore market today. Good time to sell.",
    "sec_quick": "Quick Actions",
    "act1": "Disease Predictor",
    "act2": "Crop Recommend",
    "act3": "Farm Store",
    "act4": "My Farm",
    "act5": "Farm Community",
    "act6": "Top News",
    "mandi_title": "Market Prices",
    "mandi_sub": "Live market rates · Updated daily",
    "mandi_sec_title": "Today's Rates – Indore Market",
    "mandi_h1": "Crop",
    "mandi_h2": "Price (₹/Quintal)",
    "mandi_h3": "Change",
    "mandi_h4": "Market",
    "mandi_c1": "Wheat",
    "mandi_c2": "Soybean",
    "mandi_c3": "Maize",
    "mandi_c4": "Cotton",
    "mandi_c5": "Gram",
    "mandi_c6": "Onion",
    "mandi_c7": "Tomato",
    "mandi_c8": "Potato",
    "mandi_loc1": "Indore",
    "mandi_loc2": "Bhopal",
    "mandi_loc3": "Nagpur",
    "mandi_loc4": "Nashik",
    "mandi_loc5": "Pune",
    "mandi_loc6": "Agra",
    "chat_title": "Krishi Chat AI",
    "chat_sub": "Voice assistant in English · Ask anything about farming",
    "chat_sec_title": "Chat with AI",
    "chat_welcome": "🌿 Hello Farmer! I am your Krishi AI assistant. Ask me anything about farming!",
    "chat_placeholder": "Type your question... (e.g. Which fertilizer to use for wheat?)",
    "chat_send": "Send",
    "chat_q1": "🌾 Crop disease",
    "chat_q2": "💰 Market price",
    "chat_q3": "🌱 Crop suggest",
    "chat_q4": "🌤️ Weather",
    "farm_title": "My Farm",
    "farm_sub": "Track your crops, soil, and activity",
    "farm_sec_title": "Farm Overview",
    "farm_c1_t": "Total Area",
    "farm_c1_d": "4.5 Acres – Bhopal",
    "farm_c2_t": "Active Crops",
    "farm_c2_d": "Wheat, Soybean",
    "farm_c3_t": "Soil Health",
    "farm_c3_d": "pH 6.8 – Good",
    "farm_c4_t": "Yield Est.",
    "farm_c4_d": "38 Quintal/Acre",
    "weather_title": "Live Weather",
    "weather_type": "Weather Type :",
    "weather_cond": "Haze",
    "weather_now": "Now",
    "weather_feels": "Feels Like 25.5°C",
    "weather_loc": "Bhopal , IN",
    "weather_pres": "Pressure",
    "weather_hum": "Humidity",
    "weather_wind": "Wind",
    "w_tab1": "Overview",
    "w_tab2": "Wind",
    "w_tab3": "Humidity",
    "w_d1": "Mon",
    "w_d1_desc": "scattered clouds",
    "w_d2": "Tue",
    "w_d2_desc": "few clouds",
    "w_d3": "Wed",
    "w_d3_desc": "clear sky",
    "w_d4": "Thu",
    "w_d4_desc": "clear sky",
    "w_d5": "Fri",
    "w_d5_desc": "clear sky",
    "store_title": "Farm Store",
    "store_sub": "Seeds · Fertilizers · Equipment · Delivered to your farm",
    "store_sec_title": "Featured Products",
    "s_c1_t": "Wheat Seeds HY",
    "s_c1_d": "₹1,200 / 10kg bag",
    "s_c2_t": "DAP Fertilizer",
    "s_c2_d": "₹1,350 / 50kg bag",
    "s_c3_t": "Neem Pesticide",
    "s_c3_d": "₹480 / 1L bottle",
    "s_c4_t": "Drip Kit 1 Acre",
    "s_c4_d": "₹8,500 / set",
    "s_c5_t": "Soybean Seeds",
    "s_c5_d": "₹950 / 10kg bag",
    "s_c6_t": "Soil Test Kit",
    "s_c6_d": "₹699 / kit",
    "scan_modal_title": "AI Disease Predictor",
    "scan_modal_desc": "Upload a picture of your plant leaf, and our AI will diagnose any issues.",
    "scan_upload_btn": "Select Image to Scan",
    "scan_disease": "Disease:",
    "scan_solution": "Solution:",
    "f1": "1. AI Disease Predictor",
    "f1_d": "Scan plants for diseases with AI accuracy.",
    "f2": "2. Krishi Chat AI",
    "f2_d": "Voice-enabled chatbot for help.",
    "f3": "3. Crop Recommendation",
    "f3_d": "Best crop suggestions based on soil health.",
    "f4": "4. Fertilizer Guide",
    "f4_d": "Precise NPK split info for maximum yield.",
    "f5": "5. Market Prices",
    "f5_d": "Live market rates updated daily.",
    "f6": "6. Weather Intelligence",
    "f6_d": "Hyper-local farm weather updates.",
    "f7": "7. Farm Store",
    "f7_d": "Buy seeds, fertilizers & equipment securely.",
    "f8": "8. Support System",
    "f8_d": "Direct contact with community & experts.",
    "f9": "9. Soil Testing Labs",
    "f9_d": "Find nearest certified testing facilities.",
    "f10": "10. Farm Community",
    "f10_d": "Connect with local farmers and groups.",
    "f11": "11. Govt. Subsidies",
    "f11_d": "Track schemes, grants and national orgs.",
    "f12": "12. Machinery Rental",
    "f12_d": "Rent tractors and hi-tech tools at low cost.",
    "f13": "13. Financial Ledger",
    "f13_d": "Manage farm accounts, income & expenses."
  },
  "Hindi": {
    "logo": "फार्मिफाई",
    "demo_badge": "डेमो मोड",
    "nav_home": "होम",
    "nav_mandi": "मंडी",
    "nav_chat": "चैट",
    "nav_myfarm": "मेरा खेत",
    "nav_store": "स्टोर",
    "nav_profile": "प्रोफ़ाइल",
    "hero_title": "किसान का डिजिटल साथी",
    "hero_sub": "एआई आधारित खेती सहायक · हिंदी · ऑफलाइन उपलब्ध",
    "pill_1": "120M+ उपयोगकर्ता",
    "pill_2": "3x तेज़ रोग प्रतिक्रिया",
    "pill_3": "₹15K प्रति एकड़ बचत",
    "demo_title": "डेमो: सभी 13 फीचर्स आज़माएं",
    "demo_desc": "कोई लॉगिन नहीं, तुरंत पहुंच।",
    "btn_scan": "स्कैन शुरू करें →",
    "sec_ai": "एआई फीचर्स",
    "feat1_title": "रोग पहचान",
    "feat1_desc": "तुरंत निदान के लिए पत्ती स्कैन करें",
    "feat2_title": "कृषि चैट एआई",
    "feat2_desc": "हिंदी में वॉयस असिस्टेंट",
    "feat3_title": "फसल सुझाव",
    "feat3_desc": "आपकी मिट्टी के लिए एआई फसल सुझाव",
    "feat4_title": "उर्वरक गाइड",
    "feat4_desc": "स्मार्ट उर्वरक सिफारिशें",
    "sec_advisory": "सलाह",
    "adv1_title": "🌧️ बारिश अलर्ट – भोपाल",
    "adv1_desc": "गुरुवार को हल्की बारिश की संभावना है। पानी और उर्वरक बचाने के लिए सिंचाई 2 दिन टालें।",
    "adv2_title": "🐛 कीट चेतावनी – गेहूं",
    "adv2_desc": "एमपी क्षेत्र में एफिड की गतिविधि बढ़ रही है। सर्वोत्तम परिणामों के लिए सुबह जल्दी नीम आधारित स्प्रे लगाएं।",
    "adv3_title": "💰 मंडी भाव में तेजी – सोयाबीन",
    "adv3_desc": "आज इंदौर मंडी में सोयाबीन के भाव में ₹180/क्विंटल की बढ़ोतरी। बेचने का सही समय।",
    "sec_quick": "त्वरित क्रियाएं",
    "act1": "रोग पहचान",
    "act2": "फसल सुझाव",
    "act3": "फार्म स्टोर",
    "act4": "मेरा खेत",
    "act5": "फार्म समुदाय",
    "act6": "ताज़ा खबर",
    "mandi_title": "मंडी भाव",
    "mandi_sub": "लाइव बाजार दरें · दैनिक अपडेट",
    "mandi_sec_title": "आज के भाव – इंदौर मंडी",
    "mandi_h1": "फसल",
    "mandi_h2": "भाव (₹/क्विंटल)",
    "mandi_h3": "बदलाव",
    "mandi_h4": "बाजार",
    "mandi_c1": "गेहूं",
    "mandi_c2": "सोयाबीन",
    "mandi_c3": "मक्का",
    "mandi_c4": "कपास",
    "mandi_c5": "चना",
    "mandi_c6": "प्याज",
    "mandi_c7": "टमाटर",
    "mandi_c8": "आलू",
    "mandi_loc1": "इंदौर",
    "mandi_loc2": "भोपाल",
    "mandi_loc3": "नागपुर",
    "mandi_loc4": "नासिक",
    "mandi_loc5": "पुणे",
    "mandi_loc6": "आगरा",
    "chat_title": "कृषि चैट एआई",
    "chat_sub": "हिंदी में वॉयस असिस्टेंट · खेती के बारे में कुछ भी पूछें",
    "chat_sec_title": "एआई से चैट करें",
    "chat_welcome": "🌿 नमस्ते किसान भाई! मैं आपका कृषि एआई सहायक हूँ। खेती से जुड़ी कोई भी बात पूछ सकते हो!",
    "chat_placeholder": "अपना सवाल लिखें... (उदा. गेहूं में कौन सा उर्वरक डालें?)",
    "chat_send": "भेजें",
    "chat_q1": "🌾 फसल रोग",
    "chat_q2": "💰 मंडी भाव",
    "chat_q3": "🌱 फसल सुझाव",
    "chat_q4": "🌤️ मौसम",
    "farm_title": "मेरा खेत",
    "farm_sub": "अपनी फसलें, मिट्टी और गतिविधि ट्रैक करें",
    "farm_sec_title": "खेत का अवलोकन",
    "farm_c1_t": "कुल क्षेत्र",
    "farm_c1_d": "4.5 एकड़ – भोपाल",
    "farm_c2_t": "सक्रिय फसलें",
    "farm_c2_d": "गेहूं, सोयाबीन",
    "farm_c3_t": "मिट्टी का स्वास्थ्य",
    "farm_c3_d": "pH 6.8 – अच्छा",
    "farm_c4_t": "अनुमानित उपज",
    "farm_c4_d": "38 क्विंटल/एकड़",
    "weather_title": "लाइव मौसम",
    "weather_type": "मौसम का प्रकार :",
    "weather_cond": "धुंध",
    "weather_now": "अभी",
    "weather_feels": "महसूस हो रहा है 25.5°C",
    "weather_loc": "भोपाल , IN",
    "weather_pres": "दबाव",
    "weather_hum": "नमी",
    "weather_wind": "हवा",
    "w_tab1": "अवलोकन",
    "w_tab2": "हवा",
    "w_tab3": "नमी",
    "w_d1": "सोम",
    "w_d1_desc": "बिखरे हुए बादल",
    "w_d2": "मंगल",
    "w_d2_desc": "कुछ बादल",
    "w_d3": "बुध",
    "w_d3_desc": "साफ आसमान",
    "w_d4": "गुरु",
    "w_d4_desc": "साफ आसमान",
    "w_d5": "शुक्र",
    "w_d5_desc": "साफ आसमान",
    "store_title": "फार्म स्टोर",
    "store_sub": "बीज · उर्वरक · उपकरण · आपके खेत तक डिलीवरी",
    "store_sec_title": "विशेष उत्पाद",
    "s_c1_t": "गेहूं बीज HY",
    "s_c1_d": "₹1,200 / 10kg बैग",
    "s_c2_t": "डीएपी उर्वरक",
    "s_c2_d": "₹1,350 / 50kg बैग",
    "s_c3_t": "नीम कीटनाशक",
    "s_c3_d": "₹480 / 1L बोतल",
    "s_c4_t": "ड्रिप किट 1 एकड़",
    "s_c4_d": "₹8,500 / सेट",
    "s_c5_t": "सोयाबीन बीज",
    "s_c5_d": "₹950 / 10kg बैग",
    "s_c6_t": "मिट्टी परीक्षण किट",
    "s_c6_d": "₹699 / किट",
    "scan_modal_title": "एआई रोग पहचान",
    "scan_modal_desc": "अपने पौधे की पत्ती की तस्वीर अपलोड करें, और हमारा एआई किसी भी समस्या का निदान करेगा।",
    "scan_upload_btn": "स्कैन के लिए छवि चुनें",
    "scan_disease": "बीमारी:",
    "scan_solution": "समाधान:",
    "f1": "1. एआई रोग पहचान",
    "f1_d": "एआई सटीकता के साथ पौधों के रोगों को स्कैन करें।",
    "f2": "2. कृषि चैट एआई",
    "f2_d": "मदद के लिए वॉयस-सक्षम हिंग्लिश चैटबॉट।",
    "f3": "3. फसल अनुशंसा",
    "f3_d": "मिट्टी के स्वास्थ्य के आधार पर सर्वोत्तम फसल सुझाव।",
    "f4": "4. उर्वरक गाइड",
    "f4_d": "अधिकतम उपज के लिए सटीक एनपीके जानकारी।",
    "f5": "5. मंडी भाव",
    "f5_d": "दैनिक अपडेट लाइव बाजार दरें।",
    "f6": "6. मौसम इंटेलिजेंस",
    "f6_d": "हाइपर-लोकल फार्म मौसम अपडेट।",
    "f7": "7. फार्म स्टोर",
    "f7_d": "बीज, उर्वरक और उपकरण सुरक्षित रूप से खरीदें।",
    "f8": "8. सहायता प्रणाली",
    "f8_d": "समुदाय और विशेषज्ञों के साथ सीधा संपर्क।",
    "f9": "9. मिट्टी परीक्षण प्रयोगशालाएं",
    "f9_d": "निकटतम प्रमाणित परीक्षण सुविधाएं खोजें।",
    "f10": "10. कृषि समुदाय",
    "f10_d": "स्थानीय किसानों और समूहों से जुड़ें।",
    "f11": "11. सरकारी सब्सिडी",
    "f11_d": "योजनाओं, अनुदानों और राष्ट्रीय संगठनों को ट्रैक करें।",
    "f12": "12. मशीनरी किराया",
    "f12_d": "कम लागत पर ट्रैक्टर और हाई-टेक उपकरण किराए पर लें।",
    "f13": "13. वित्तीय बहीखाता",
    "f13_d": "खेत के खातों, आय और व्यय का प्रबंधन करें।"
  }
};

function changeLanguage(lang) {
  currentLang = lang;
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      el.innerText = translations[lang][key];
    }
  });

  const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
  placeholders.forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (translations[lang] && translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });

  if (typeof fetchAdvisories === 'function') {
    fetchAdvisories();
  }
}

// Initialize on load if there's a default set in select
window.addEventListener('DOMContentLoaded', () => {
  const select = document.getElementById('langSelect');
  if (select) {
    changeLanguage(select.value);
  }
});
